import { useCallback, useEffect, useMemo, useRef, useState } from "react";

import {
  MEALS,
  type DailyMenu,
  type MealName,
  type MealPlan,
  type Profile,
} from "@/lib/mess-types";

import {
  computeTargets,
  generatePlan,
  totalsFor,
} from "@/lib/nutrition";

import { getLocalDateKey } from "@/lib/date";
import { swapMealItem } from "@/lib/swapMeal";

const PLAN_STORAGE_KEY = "meal-plan";

function loadSavedPlan(): MealPlan | null {
  if (typeof window === "undefined") return null;

  const saved = localStorage.getItem(PLAN_STORAGE_KEY);
  if (!saved) return null;

  try {
    const parsed = JSON.parse(saved) as { date: string; plan: MealPlan };
    if (parsed.date !== getLocalDateKey()) {
      localStorage.removeItem(PLAN_STORAGE_KEY);
      return null;
    }
    return parsed.plan;
  } catch {
    return null;
  }
}

export function useMealPlanner(
  profile: Profile | null | undefined,
  menu: DailyMenu | undefined,
) {
  const [generating, setGenerating] = useState(false);
  const [plan, setPlan] = useState<MealPlan | null>(loadSavedPlan);
  const autoGenerated = useRef(false);

  const targets = useMemo(
    () => (profile ? computeTargets(profile) : null),
    [profile],
  );

  const generate = useCallback(() => {
    if (!targets || !menu?.items.length) return;

    setGenerating(true);
    setPlan(generatePlan(menu.items, targets));
    setTimeout(() => setGenerating(false), 250);
  }, [targets, menu]);

  const swap = useCallback(
    (meal: MealName, oldId: string, newId: string) => {
      if (!plan || !menu) return;
      setPlan(swapMealItem(plan, meal, oldId, newId, menu.items));
    },
    [plan, menu],
  );

  const dayTotals = useMemo(() => {
    if (!menu || !plan) {
      return { calories: 0, protein: 0, carbs: 0, fat: 0 };
    }

    return MEALS.map((meal) => totalsFor(plan[meal] ?? [], menu.items)).reduce(
      (a, b) => ({
        calories: a.calories + b.calories,
        protein: a.protein + b.protein,
        carbs: a.carbs + b.carbs,
        fat: a.fat + b.fat,
      }),
      { calories: 0, protein: 0, carbs: 0, fat: 0 },
    );
  }, [plan, menu]);

  useEffect(() => {
    if (!plan) return;
    localStorage.setItem(
      PLAN_STORAGE_KEY,
      JSON.stringify({ date: getLocalDateKey(), plan }),
    );
  }, [plan]);

  // Auto-generate once when profile + menu are ready and no saved plan
  useEffect(() => {
    if (autoGenerated.current || plan || !targets || !menu?.items.length) return;
    autoGenerated.current = true;
    generate();
  }, [plan, targets, menu, generate]);

  return {
    targets,
    plan,
    generating,
    dayTotals,
    generate,
    swap,
  };
}
