import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";

import {
  MEALS,
  type DailyMenu,
  type MealName,
  type MealPlan,
  type Profile,
} from "@/lib/mess-types";

import {
  computeTargets,
  generatePlan,
  totalsFor,
} from "@/lib/nutrition";

import { getLocalDateKey } from "@/lib/date";
import { swapMealItem } from "@/lib/swapMeal";

const PLAN_STORAGE_KEY = "meal-plan";
const HIGH_TEA_STORAGE_KEY = "include-high-tea";

function loadSavedPlan(): MealPlan | null {
  if (typeof window === "undefined") return null;

  const saved = localStorage.getItem(
    PLAN_STORAGE_KEY,
  );

  if (!saved) return null;

  try {
    const parsed = JSON.parse(saved) as {
      date: string;
      plan: MealPlan;
    };

    if (
      parsed.date !== getLocalDateKey()
    ) {
      localStorage.removeItem(
        PLAN_STORAGE_KEY,
      );
      return null;
    }

    return parsed.plan;
  } catch {
    return null;
  }
}

function loadHighTeaPreference(): boolean {
  if (typeof window === "undefined") {
    return true;
  }

  const saved = localStorage.getItem(
    HIGH_TEA_STORAGE_KEY,
  );

  // High Tea is ON by default.
  return saved !== "false";
}

export function useMealPlanner(
  profile: Profile | null | undefined,
  menu: DailyMenu | undefined,
) {
  const [generating, setGenerating] =
    useState(false);

  const [plan, setPlan] =
    useState<MealPlan | null>(
      loadSavedPlan,
    );

  const [includeHighTea, setIncludeHighTea] =
    useState(loadHighTeaPreference);

  const autoGenerated = useRef(false);

  const targets = useMemo(
    () =>
      profile
        ? computeTargets(profile)
        : null,
    [profile],
  );

  /*
   * Generate a completely new plan.
   *
   * This is used for the main "Generate Plan"
   * button, so all meals can be generated.
   */
  const generate = useCallback(() => {
    if (
      !targets ||
      !menu?.items.length
    ) {
      return;
    }

    setGenerating(true);

    setPlan(
      generatePlan(
        menu.items,
        targets,
        includeHighTea,
      ),
    );

    setTimeout(
      () => setGenerating(false),
      250,
    );
  }, [
    targets,
    menu,
    includeHighTea,
  ]);

  /*
   * Toggle High Tea.
   *
   * Breakfast is deliberately preserved.
   *
   * This matters because a student may already
   * have eaten breakfast before deciding whether
   * they want High Tea later.
   */
  const toggleHighTea = useCallback(
    () => {
      if (
        !targets ||
        !menu?.items.length
      ) {
        return;
      }

      const nextValue =
        !includeHighTea;

      setIncludeHighTea(nextValue);

      setPlan((currentPlan) => {
        if (!currentPlan) {
          return currentPlan;
        }

        const newPlan = generatePlan(
          menu.items,
          targets,
          nextValue,
        );

        /*
         * Keep the existing breakfast exactly
         * as it is.
         */
        return {
          ...newPlan,
          breakfast:
            currentPlan.breakfast ?? [],
        };
      });
    },
    [
      includeHighTea,
      targets,
      menu,
    ],
  );

  const swap = useCallback(
    (
      meal: MealName,
      oldId: string,
      newId: string,
    ) => {
      if (!plan || !menu) return;

      setPlan(
        swapMealItem(
          plan,
          meal,
          oldId,
          newId,
          menu.items,
        ),
      );
    },
    [plan, menu],
  );

  const increaseServing = useCallback(
    (
      meal: MealName,
      itemId: string,
    ) => {
      if (!plan) return;

      setPlan({
        ...plan,
        [meal]: plan[meal].map(
          (entry) =>
            entry.itemId === itemId
              ? {
                  ...entry,
                  servings:
                    entry.servings + 1,
                }
              : entry,
        ),
      });
    },
    [plan],
  );

  const decreaseServing = useCallback(
    (
      meal: MealName,
      itemId: string,
    ) => {
      if (!plan) return;

      setPlan({
        ...plan,
        [meal]: plan[meal]
          .map((entry) =>
            entry.itemId === itemId
              ? {
                  ...entry,
                  servings:
                    Math.max(
                      0.5,
                      entry.servings - 1,
                    ),
                }
              : entry,
          )
          .filter(
            (entry) =>
              entry.servings > 0,
          ),
      });
    },
    [plan],
  );

  const dayTotals = useMemo(() => {
    if (!menu || !plan) {
      return {
        calories: 0,
        protein: 0,
        carbs: 0,
        fat: 0,
      };
    }

    return MEALS.map((meal) =>
      totalsFor(
        plan[meal] ?? [],
        menu.items,
      ),
    ).reduce(
      (a, b) => ({
        calories:
          a.calories + b.calories,
        protein:
          a.protein + b.protein,
        carbs:
          a.carbs + b.carbs,
        fat:
          a.fat + b.fat,
      }),
      {
        calories: 0,
        protein: 0,
        carbs: 0,
        fat: 0,
      },
    );
  }, [plan, menu]);

  /*
   * Save the meal plan.
   */
  useEffect(() => {
    if (!plan) return;

    localStorage.setItem(
      PLAN_STORAGE_KEY,
      JSON.stringify({
        date: getLocalDateKey(),
        plan,
      }),
    );
  }, [plan]);

  /*
   * Save High Tea preference.
   */
  useEffect(() => {
    localStorage.setItem(
      HIGH_TEA_STORAGE_KEY,
      String(includeHighTea),
    );
  }, [includeHighTea]);

  /*
   * Auto-generate once when profile + menu
   * are ready and no saved plan exists.
   */
  useEffect(() => {
    if (
      autoGenerated.current ||
      plan ||
      !targets ||
      !menu?.items.length
    ) {
      return;
    }

    autoGenerated.current = true;
    generate();
  }, [
    plan,
    targets,
    menu,
    generate,
  ]);

  return {
    targets,
    plan,
    generating,
    dayTotals,
    includeHighTea,
    generate,
    toggleHighTea,
    swap,
    increaseServing,
    decreaseServing,
  };
}